services:
  cloudflare-dyndns:
    image: ghcr.io/vrail3/cfgo-dyndns:latest
    container_name: cfgo-dyndns
    ports:
      - "80:8080"
    restart: unless-stopped
    environment:
      CF_ZONE: "example.com"
      # set either full subdomain or root domain
      CF_RECORD: "subdomain.example.com"
      CF_API_KEY: "your-cloudflare-api-key"
      # the key for the app to authenticate NOT the cloudflare api key
      APP_KEY: "your-app-api-key"
      # TZ for correct logging timestamps
      TZ: "Europe/Berlin"